### PR TITLE
Convert to TypeScript

### PR DESCRIPTION
**Pull request by sharplet**
This change configures the project for TypeScript and then adds type definitions for the redux modules and screen components. See commit log for more info.

Depends on #35.

### CODE REVIEW

**Comment by sharplet** [comment]
Unfortunately the commits are a little messy here: I had to do a lot of debugging to get this into a working state, and it would be _really_ time-consuming to go back and try and tease apart the slightly related but slightly different changes. Having said that, I think this is in a good position to move forward!

**Comment by gfontenot** [comment]
Do files need the `tsx` file extension? Why not `ts`?

**Comment by sharplet** [comment]
TypeScript doesn't appear to support JSX in .ts files, and I haven't found an option to change that behaviour yet. I decided I didn't mind the explicitness of using the .tsx extension.

**Comment by tabfugnic** [comment]
This might be something that has been talked about, but can you explain the advantages of using TypeScript over say JSX or anything else? I don't know that I understand the need for this change.

**Comment by sharplet** [comment]
The lack of a strong type system is something that I've felt quite keenly while working in straight JS/JSX (compared to the native development I've done in Swift). The main problem this solves for me is a lack of confidence in refactoring RN apps as they grow. Another way to help solve the same problem would be to have strong integration/feature tests — but while this (TypeScript) was difficult to get configured, a reliable mobile UI test suite is even harder to set up and maintain. So the benefit is you get greater confidence maintaining the code, but with a tighter feedback loop and less ongoing maintenance than feature tests.

> ... can you explain the advantages of using TypeScript over say JSX or anything else?

FWIW, now having explained what I believe to be the benefits of a strong type system, I think a more apples-to-apples comparison would be with [Flow][], which is the main alternative in React Native apps. I think either would do the job, but anecdotally my understanding is that TypeScript has a few more features.

This PR is more about getting a working TypeScript setup that can be easily replicated for new projects, so that we can hit the ground running and really test whether it's the right tool for the job.

[Flow]: https://flow.org

**Review by sidraval — APPROVED** [review]
Even knowing that this is possible makes me significantly less anxious about working on a React Native project. Thanks @sharplet !

**Comment by mwenger1** [comment]
Wanted to share this relevant quote from [an article](https://blog.mariusschulz.com/2017/01/13/typescript-vs-flow#deciding-between-typescript-and-flow) I just read.

> If you're working with Angular 2+, you might favor TypeScript because it's the dominant language used in the Angular community. If you're using React, on the other hand, you might prefer Flow because it easily integrates with Babel and other infrastructure you probably already have in place.

I don't know enough about the differences between Typescript vs Flow to have an opinion. Was curious if you had considered Flow, and if yes, what factors led you to pick Typescript

**Comment by sharplet** [comment]
@mwenger1 My choice to try out TypeScript was based on a brief initial experience trying to integrate both it and Flow. I ultimately had a better experience with TypeScript, and felt like I was getting better feedback from it. However, I didn't spend a lot of time on it, so it's possible I could have been missing something obvious.

Additionally, I believe that TypeScript has more features, being a superset of JavaScript rather than just a typechecker.

**Comment by sidraval** [comment]
I went through the setup in the README, but `react-native run-ios` did not end up producing a working example application for me.

- XCode 9.0.1
- yarn 1.2.1
- react-native-cli 2.0.1

screen shot 2017-10-28 at 3 51 16 pm

Ouput of launchPackager:

```
➜  ~ /Users/sid/c/costar-react-native/node_modules/react-native/packager/launchPackager.command ; exit;

~/c/costar-react-native/node_modules/react-native/packager ~
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/sid/c/costar-react-native/node_modules/react-native/packager 


React packager ready.

Loading dependency graph, done.
error: bundling: NotFoundError: Cannot find entry file index.ios.js in any of the roots: ["/Users/sid/c/costar-react-native/node_modules/react-native/packager"]
    at DependencyGraph._getAbsolutePath (/Users/sid/c/costar-react-native/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:280:11)
    at DependencyGraph.getDependencies (/Users/sid/c/costar-react-native/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:218:26)
    at Resolver.getDependencies (/Users/sid/c/costar-react-native/node_modules/react-native/packager/src/Resolver/index.js:107:27)
    at /Users/sid/c/costar-react-native/node_modules/react-native/packager/src/Bundler/index.js:591:37
    at Generator.next (<anonymous>)
    at step (/Users/sid/c/costar-react-native/node_modules/react-native/packager/src/Bundler/index.js:12:445)
    at /Users/sid/c/costar-react-native/node_modules/react-native/packager/src/Bundler/index.js:12:605
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Bundling `index.ios.js`  0.0% (0/1), failed.
error: bundling: NotFoundError: Cannot find entry file index.ios.js in any of the roots: ["/Users/sid/c/costar-react-native/node_modules/react-native/packager"]
    at DependencyGraph._getAbsolutePath (/Users/sid/c/costar-react-native/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:280:11)
    at DependencyGraph.getDependencies (/Users/sid/c/costar-react-native/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:218:26)
    at Resolver.getDependencies (/Users/sid/c/costar-react-native/node_modules/react-native/packager/src/Resolver/index.js:107:27)
    at /Users/sid/c/costar-react-native/node_modules/react-native/packager/src/Bundler/index.js:591:37
    at Generator.next (<anonymous>)
    at step (/Users/sid/c/costar-react-native/node_modules/react-native/packager/src/Bundler/index.js:12:445)
    at /Users/sid/c/costar-react-native/node_modules/react-native/packager/src/Bundler/index.js:12:605
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Bundling `index.ios.js`  0.0% (0/1), failed.

```

**Review by sidraval — COMMENTED** [review]
I think `TemplateProject/` needs to be copied into `{{cookiecutter.directory_name}}` before this can be merged.

**Comment by purinkle** [comment]
[Convert to TypeScript](https://trello.com/c/GmVUHIMe/19-convert-to-typescript)

**Pull request closed without merging**
